services:
  db:
    image: pgvector/pgvector:pg15
    container_name: api_governance_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: api_governance_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  ollama:
    image: ollama/ollama
    container_name: api_governance_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped 

  backend:
    build: ./Backend
    container_name: api_governance_backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:admin123@db:5432/api_governance_db
      OLLAMA_URL: http://ollama:11434/api/generate 
    depends_on:
      - db
      - ollama

  wso2am:
    build: ./WSO2
    container_name: api_governance_wso2
    environment:
      # Providing the heap space needed for UI extraction
      - JVM_MEM_OPTS=-Xms2g -Xmx3g 
      - NODE_IP=0.0.0.0
    ports:
      - "9443:9443"
      - "8243:8243"
      - "8280:8280"
    volumes:
      - wso2_data:/home/wso2carbon/wso2am-4.6.0/repository/database
    deploy:
      resources:
        limits:
          memory: 4G
    restart: always

volumes:
  ollama_data:
  db_data:
  wso2_data: